### PR TITLE
Add assets

### PR DESCRIPTION
**Pull request by tramuntanal**
Added a couple of icons so that code that uses the gem can use them.

### CODE REVIEW

**Comment by tramuntanal** [comment]
@isaacmg410 @MarcReniu do you think the assets are placed in the best location? would you suggest some other place or you find it ok?

**Review by isaacmg410 — CHANGES_REQUESTED** [review]
Please, ask the designers to export correctly the svg's. It's not good to see 'id= "Capa_1"'.
Also, I think that you need to add these files to manifest, for asset:precompile, no?

**Comment by isaacmg410** [comment]
@tramuntanal is it ok for me.

**Comment by tramuntanal** [comment]
Hi @isaacmg410 
I already asked for

**Comment by tramuntanal** [comment]
@isaacmg410 I've updated the assets and the README.
Can you approve?

**Review by isaacmg410 — APPROVED** [review]

**Comment by isaacmg410** [comment]
@tramuntanal Good job! You can merge it :smile:

**Pull request merged**
